### ISSUE TITLE
Problem with permission

### ISSUE THREAD

**Issue by Horld3n** [filbert66/EnchantLimiter#1]
Replace
`
        if ( !getConfig().getBoolean ("Stop pickup") && player.hasPermission ("enchlimiter.useillegal"))
            return;
`

to

`
        if ( !getConfig().getBoolean ("Stop pickup") || player.hasPermission ("enchlimiter.useillegal"))
            return;
`

**Comment by filbert66** [comment]
_useillegal_ is intended to allow them use an illegal item, but **Stop pickup** = _true_ can avoid them even picking it up. If you really want a permission to allow them to pick up an illegal item, we should add a new _pickupillegal_

Description on main page:

> **enchlimiter.useillegal** permits equipping/holding illegal items when **Fix held items** is _false_. [1.5.4]

**Comment by filbert66** [comment]
BTW, thanks much for the comment on my code!

**Comment by Horld3n** [comment]
I have add an exception for world "animation"
