### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by ItsHarry** [filbert66/EnchantLimiter#2]
Sometimes when a disallowed enchant is removed from an item, the item can be duplicated.

It happens in this video at 0:46 seconds:
https://www.youtube.com/watch?v=gPiS-IMfsUs

**Comment by filbert66** [comment]
Hmm... Can you explain in more detail what you did? Looks like you took a disallowed result by shift-click and then it appeared again without. Could be timing-related.

**Comment by ItsHarry** [comment]
Well I didn't record the video myself, but yes it's a shift-click. Then it removes the disallowed enchant and magically there's a duplicated item all of a sudden

**Comment by filbert66** [comment]
Hi Harry, I have a draft fix. I think it has to do with an event handle that spawned a task to give the item back, but it wasn't checking if the player took it already. It only would happen on busy servers that give the player a chance to take the item before the event runs (in one tick!), so it's really hard for me to confirm is fixed. But I think this if statement will do it.

``` java
// Execute limit
if (iInventory.getItem() == null || iInventory.getItem().getType() != limitedItem.getType())
{ // They took item before we could give it back.
    log.warning (language.get (player, "theft", "{0} closed inventory or table died and got an illegal item: {1}", player.getName(), limitedItem.getType()));
    return;
} // else
iInventory.setItem (limitedItem); // give properly enchanted item back.
```

Let me know if you see the bug still.
